### ISSUE TITLE
http-outgoing Content-Type: text/html; charset=ISO-8859-1?

### ISSUE THREAD

**Issue by christopher-johnson** [fcrepo4-exts/fcrepo-camel-toolbox#83] opened 2016-04-15 12:22 UTC
When indexing content from fcrepo into fuseki, the wide (Unicode) chars become mangled.  I suspect that this may have something to do with the default apache.httpcomponents.httpclient configuration.  I see this in the Karaf log:
`2016-04-15 13:53:38,715 | DEBUG | Consumer[fedora] | headers                          | 79 - org.apache.httpcomponents.httpclient - 4.5.2 | http-outgoing-1388 << Content-Type: text/html;charset=ISO-8859-1`
and
`2016-04-15 13:36:25,336 | DEBUG | Consumer[fedora] | wire                             | 79 - org.apache.httpcomponents.httpclient - 4.5.2 | http-outgoing-113 << "[0x9]blume:a22 """Spengel, J.W. (1877): Die von Blumenbach gegr[0xc3][0xbc]ndete anthropologische Sammlung der Universit[0xc3][0xa4]t G[0xc3][0xb6]ttingen. Aufgenommen im Jahre 1874. [In:] Schaafhausen, H. (Hrsg.): Die[\n]"`

I am using fcrepo and fuseki in tomcat7 and I am pretty sure that there are no encoding issues there.  Everything renders properly from fcrepo, and when I import a ttl file into fuseki directly, the wide characters are maintained.  Also, when I use a rest client for a GET from fuseki, it returns Content-Type: UTF-8.

It may not be an issue with your code, but maybe you can tell me where else to look.  Thanks.

**Comment by acoburn** [comment] 2016-04-15 13:29
@christopher-johnson you are correct: unicode values get mangled when they are pushed to an external component. You can track this issue in this ticket: https://jira.duraspace.org/browse/FCREPO-1991

The issue is due to this (and other such) lines in `fcrepo-camel`: https://git.io/vwkCg.
The `fcrepo-camel-toolbox` integrations can be fixed immediately by overriding the `Content-Type` header here: https://git.io/vwkCx

Might you be interested in contributing the fix for this? Otherwise, I can take care of this.

**Comment by acoburn** [comment] 2016-04-15 14:36
The issue will be resolved with this PR: https://github.com/fcrepo4-exts/fcrepo-camel/pull/107 and will be part of the next release of `fcrepo-camel`.

**Comment by acoburn** [comment] 2016-04-15 14:37
Thanks for reporting this @christopher-johnson!

**Closed by acoburn** 2016-04-15 14:36 UTC
